"""Rule C15 (task 115): unsupported_program_id_divergence.

Detects unknown-program guard paths that return a generic error code instead of
ERR_UNSUPPORTED_PROGRAM_ID, which can diverge from Agave error priority.

This rule uses minimal dataflow facts generated by the C adapter:
- program_guard_sites
- return_error_codes
"""

from smartgraphical.core.engine import make_findings

_BAD_ERROR_CODES = frozenset({
    'ERR_NOT_FOUND',
    'ERR_INVALID',
    'ERR_UNKNOWN',
    'ACCOUNT_NOT_FOUND',
    'ERR_PROGRAM_NOT_FOUND',
})
_GOOD_ERROR_CODE = 'ERR_UNSUPPORTED_PROGRAM_ID'

_META = dict(
    task_id='115',
    legacy_code=115,
    slug='unsupported_program_id_divergence',
    title='Semantic Mismatch on UnsupportedProgramId Error',
    category='consensus_failure',
    portability='portable_with_adapter',
    confidence='high',
    remediation_hint=(
        'Return ERR_UNSUPPORTED_PROGRAM_ID on unknown program paths to match '
        'Agave priority.'
    ),
)


def _detect(context):
    alerts = []
    model = context.normalized_model
    function_facts = getattr(model.findings_data, 'function_facts', {})
    for type_entry in model.types:
        for function in type_entry.functions:
            function_key = f"{type_entry.name}.{function.name}"
            facts = function_facts.get(function_key, {})
            dataflow = facts.get('dataflow', {})
            guard_sites = dataflow.get('program_guard_sites', [])
            return_sites = dataflow.get('return_error_codes', [])
            if not guard_sites or not return_sites:
                continue
            for guard in guard_sites:
                guard_idx = guard.get('statement_index', -1)
                nearby_returns = [
                    ret for ret in return_sites
                    if guard_idx <= ret.get('statement_index', -1) <= guard_idx + 2
                ]
                for ret in nearby_returns:
                    code = ret.get('code', '')
                    if code == _GOOD_ERROR_CODE:
                        continue
                    if code in _BAD_ERROR_CODES:
                        alerts.append({
                            'code': 115,
                            'message': (
                                f"Unknown program path returns '{code}' instead of "
                                f"'{_GOOD_ERROR_CODE}' in {function_key}: "
                                f"{ret.get('statement', '')[:120]}"
                            ),
                        })
    return alerts


def run(context):
    return make_findings(_detect(context), context.normalized_model, **_META)
